version: '3'
services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: tsuyoponta4127
      MYSQL_DATABASE: root
    ports:
      - "4307:3306"
    volumes:
      - ./tmp/db:/var/lib/mysql
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/citem
    ports:
      - "3001:3000"
    depends_on:
      - db
